# Generated by Django 5.1.1 on 2024-09-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_active_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['pk']},
        ),
    ]
